news:
  view:
    layoutRootPath: 'EXT:headless_news/Resources/Private/News/Layouts/'
    partialRootPath: 'EXT:headless_news/Resources/Private/News/Partials/'
    templateRootPath: 'EXT:headless_news/Resources/Private/News/Templates/'
