news:
  view:
    layoutRootPath: 'EXT:headless_news/Resources/Private/Layouts/News/'
    partialRootPath: 'EXT:headless_news/Resources/Private/Partials/News/'
    templateRootPath: 'EXT:headless_news/Resources/Private/Templates/News/'
